#!/bin/bash

openjdk=openjdk
if [[ $(uname -m) = aarch64 ]]; then
    openjdk=arm64v8/openjdk
fi

mkdir data logs db || exit 1
cp system.properties data || exit 1

podman --runtime crun pod create \
    -n unifi-pod \
    --publish 1900/udp \
    --publish 3478/udp \
    --publish 5656-5699/udp \
    --publish 8080 \
    --publish 8443 \
    --publish 10001/udp \
    || exit 1

podman --runtime crun create \
    --name unifi-db \
    --pod unifi-pod \
    --uidmap 0:1:999 \
    --uidmap 999:0:1 \
    -v ./db:/data/db:z \
    mongo:3 \
    || exit 1

podman --runtime crun create \
    --name unifi \
    --pod unifi-pod \
    -v ./logs:/unifi/logs:z \
    -v ./data:/unifi/data:z \
    -v ./unifi:/unifi \
    -w /unifi \
    $openjdk:8 \
    java -jar lib/ace.jar start \
    || exit 1
